apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay
  namespace: quay-enterprise
spec:
  clair:
    enabled: true
    resources: {}
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 6061
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 5
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 6061
        scheme: HTTP
      initialDelaySeconds: 30
      timeoutSeconds: 5
    deploymentStrategy: RollingUpdate
    envVars:
      - name: HTTP_PROXY
        value: 'http://rhocp_poc_svc:RedHat123+@10.194.93.35:8080'
      - name: HTTPS_PROXY
        value: 'http://rhocp_poc_svc:RedHat123+@10.194.93.35:8080'
      - name: NO_PROXY
        value: >-
          .cluster.local,.corpdev.hkjc.com,.rhocp.hkjc,.svc,10.0.0.0/16,10.128.0.0/14,10.194.176.0/24,127.0.0.1,172.30.0.0/16,api-int.poc1.rhocp.hkjc,etcd-0.poc1.rhocp.hkjc,etcd-1.poc1.rhocp.hkjc,etcd-2.poc1.rhocp.hkjc,localhost
    image: 'quay.io/redhat/clair-jwt:v3.3.1'
    database:
      deploymentStrategy: RollingUpdate
      image: 'registry.access.redhat.com/rhscl/postgresql-96-rhel7:1'
      livenessProbe:
        exec:
          command:
            - /usr/libexec/check-container
            - '--live'
        failureThreshold: 3
        initialDelaySeconds: 120
        timeoutSeconds: 10
      readinessProbe:
        exec:
          command:
            - /usr/libexec/check-container
        failureThreshold: 3
        initialDelaySeconds: 10
        timeoutSeconds: 1
      resources: {}
      volumeSize: 50Gi
    imagePullSecretName: redhat-pull-secret
  quay:
    configResources: {}
    resources: {}
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health/instance
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 5
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health/instance
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 120
      timeoutSeconds: 5
    migrationPhase: new-installation
    superusers:
      - quay
    externalAccess:
      hostname: quay.apps.poc1.rhocp.hkjc
      tls:
        termination: passthrough
      type: Route
    repoMirrorResources: {}
    deploymentStrategy: Recreate
    image: 'quay.io/redhat/quay:v3.3.1'
    database:
      deploymentStrategy: RollingUpdate
      image: 'registry.access.redhat.com/rhscl/postgresql-96-rhel7:1'
      livenessProbe:
        exec:
          command:
            - /usr/libexec/check-container
            - '--live'
        failureThreshold: 3
        initialDelaySeconds: 120
        timeoutSeconds: 10
      readinessProbe:
        exec:
          command:
            - /usr/libexec/check-container
        failureThreshold: 3
        initialDelaySeconds: 10
        timeoutSeconds: 1
      resources: {}
      volumeSize: 50Gi
    imagePullSecretName: redhat-pull-secret
    registryBackends:
      - local:
          storagePath: /datastorage/registry
        name: default
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
      persistentVolumeSize: 200Gi
  redis:
    deploymentStrategy: RollingUpdate
    image: 'registry.access.redhat.com/rhscl/redis-32-rhel7:latest'
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      tcpSocket:
        port: 6379
    resources: {}